# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
import numpy as np

# Print numpy version
print("Numpy version:", np.__version__)

# Print numpy configuration
print("Numpy configuration:", np.__config__.show())



Numpy version: 2.0.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "l

/Users/amanialshaikh/Library/Python/3.9/lib/python/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
import numpy as np

# Method 1: Using np.random.rand()
a_rand = np.random.rand(2, 3, 5)
print("Using np.random.rand():\n", a_rand)

# Method 2: Using np.random.randn()
a_randn = np.random.randn(2, 3, 5)
print("\nUsing np.random.randn():\n", a_randn)

# Method 3: Using np.random.random()
a_random = np.random.random((2, 3, 5))
print("\nUsing np.random.random():\n", a_random)



Using np.random.rand():
 [[[0.86545489 0.52400869 0.37963522 0.06386432 0.09143375]
  [0.80453156 0.8336031  0.45846409 0.76017007 0.90819691]
  [0.88825281 0.84222222 0.94639923 0.11745611 0.24898267]]

 [[0.45672698 0.24600849 0.72907526 0.05706793 0.81309349]
  [0.89689947 0.66489693 0.77417767 0.4307765  0.98733536]
  [0.44959856 0.79298454 0.68295713 0.37539338 0.46444599]]]

Using np.random.randn():
 [[[ 0.86119598 -1.77055971 -0.29480462  1.57873045 -1.23212602]
  [-0.89843078  0.43445164  0.43217569  0.1853388   1.30155093]
  [ 0.37028785 -0.21670403 -0.74148755  0.15079187  0.78013884]]

 [[-0.40512675  1.63721737 -1.52663031 -2.09777952  1.04819613]
  [-0.8511727   1.47371333  3.07614261  0.08253865 -0.53479535]
  [-1.1628611   0.2851776  -0.90095851  0.71500803  1.91764325]]]

Using np.random.random():
 [[[0.56140425 0.80904657 0.39901576 0.77510853 0.01666849]
  [0.21049186 0.81412672 0.34577175 0.52769718 0.03024245]
  [0.62932187 0.74391874 0.50785871 0.46751773 0.9436367


### 4. Print a.


In [4]:
### [your code here]
import numpy as np

# Generating a 2x3x5 random array using np.random.rand()
a = np.random.rand(2, 3, 5)

# Printing the array a
print("Array a:\n", a)


Array a:
 [[[5.46471528e-01 3.27163183e-01 1.10252585e-02 6.56417672e-01
   2.63367307e-01]
  [9.55668755e-01 7.89896188e-01 6.21650937e-01 2.44914290e-01
   5.31642961e-01]
  [2.53811692e-01 4.51139176e-01 2.04624176e-01 7.54521857e-02
   7.41547177e-01]]

 [[2.60943624e-01 3.86565674e-01 9.46578471e-01 2.01453647e-01
   7.93296608e-01]
  [8.20094052e-01 7.01341828e-01 8.95348138e-01 5.33201449e-01
   2.53640262e-01]
  [4.43378062e-01 7.60787086e-01 5.83360036e-01 1.92248114e-01
   6.12458933e-04]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
import numpy as np

# Creating a 5x2x3 array with all values equal to 1
b = np.ones((5, 2, 3))

# Printing the array b
print("Array b:\n", b)


Array b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [6]:
### [your code here]
import numpy as np

# Create the 5x2x3 array with all values equal to 1 and print it
print("Array b:\n", np.ones((5, 2, 3)))



Array b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
### [your code here]
import numpy as np

# Generate the 2x3x5 array for a and the 5x2x3 array for b
a = np.random.rand(2, 3, 5)  # Example array a
b = np.ones((5, 2, 3))  # Array b

# Check if a and b have the same size
print("Do a and b have the same size?", a.shape == b.shape)



Do a and b have the same size? False


In [9]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)


Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)



### 8. Are you able to add a and b? Why or why not?


In [10]:
### [your code here]
import numpy as np

# Create array a and b
a = np.random.rand(2, 3, 5)  # Shape (2, 3, 5)
b = np.ones((5, 2, 3))  # Shape (5, 2, 3)

# Check if the arrays can be added
try:
    result = a + b
    print("Arrays a and b can be added.")
except ValueError as e:
    print(f"Error: {e}")



Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
import numpy as np

# Create array b with shape (5, 2, 3)
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = np.transpose(b, (1, 2, 0))

# Print the transposed array c
print("Transposed array c with shape", c.shape)
print(c)



Transposed array c with shape (2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [14]:
### [your code here]
import numpy as np

# Create array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)

# Create array b with shape (5, 2, 3)
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = np.transpose(b, (1, 2, 0))

# Add a and c
d = a + c

# Print the result
print("Array d (sum of a and c):")
print(d)



Array d (sum of a and c):
[[[1.52551894 1.08728389 1.54746002 1.41482029 1.51715502]
  [1.97925244 1.31717203 1.38683503 1.24537308 1.29130933]
  [1.69259125 1.76429593 1.56471189 1.92576953 1.29484073]]

 [[1.63375537 1.56899756 1.57027333 1.23472388 1.23900893]
  [1.36097084 1.9004949  1.88054783 1.69828641 1.22033657]
  [1.19714167 1.4821865  1.96022631 1.132951   1.11032192]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [15]:
### [your code here]
import numpy as np

# Create array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)

# Create array b with shape (5, 2, 3)
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = np.transpose(b, (1, 2, 0))

# Add a and c to get d
d = a + c

# Print a and d
print("Array a:")
print(a)

print("\nArray d (sum of a and c):")
print(d)




Array a:
[[[0.0518145  0.77763945 0.15895751 0.34511432 0.87029493]
  [0.9671362  0.15291426 0.96352046 0.74291333 0.93025035]
  [0.55454039 0.67018775 0.89099883 0.6705905  0.09268978]]

 [[0.51032892 0.11495435 0.13574917 0.37161889 0.90603955]
  [0.48841893 0.46976114 0.73826919 0.47130551 0.79173891]
  [0.86037662 0.32463623 0.18428464 0.69325645 0.05285976]]]

Array d (sum of a and c):
[[[1.0518145  1.77763945 1.15895751 1.34511432 1.87029493]
  [1.9671362  1.15291426 1.96352046 1.74291333 1.93025035]
  [1.55454039 1.67018775 1.89099883 1.6705905  1.09268978]]

 [[1.51032892 1.11495435 1.13574917 1.37161889 1.90603955]
  [1.48841893 1.46976114 1.73826919 1.47130551 1.79173891]
  [1.86037662 1.32463623 1.18428464 1.69325645 1.05285976]]]



### 12. Multiply a and c. Assign the result to e.


In [17]:
### [your code here]
import numpy as np

# Create array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)

# Create array b with shape (5, 2, 3)
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = np.transpose(b, (1, 2, 0))

# Multiply a and c to get e
e = a * c

# Print the result
print("Array a:")
print(a)

print("\nArray c:")
print(c)

print("\nArray e (result of a * c):")
print(e)



Array a:
[[[0.59326016 0.13608674 0.12551519 0.08901926 0.32216637]
  [0.67652318 0.62190144 0.47246425 0.15042165 0.10683963]
  [0.1060509  0.47946997 0.02265766 0.05338122 0.09492863]]

 [[0.20344244 0.18151441 0.22034244 0.55202456 0.70269839]
  [0.37641246 0.14954011 0.43849995 0.59792229 0.29861257]
  [0.55737894 0.96486411 0.52905842 0.26630666 0.36676463]]]

Array c:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Array e (result of a * c):
[[[0.59326016 0.13608674 0.12551519 0.08901926 0.32216637]
  [0.67652318 0.62190144 0.47246425 0.15042165 0.10683963]
  [0.1060509  0.47946997 0.02265766 0.05338122 0.09492863]]

 [[0.20344244 0.18151441 0.22034244 0.55202456 0.70269839]
  [0.37641246 0.14954011 0.43849995 0.59792229 0.29861257]
  [0.55737894 0.96486411 0.52905842 0.26630666 0.36676463]]]




### 13. Does e equal to a? Why or why not?


In [18]:
### [your code here]
import numpy as np

# Create a random array a
a = np.random.rand(2, 3, 5)

# Create array b with shape (5, 2, 3) and transpose it to match a's shape
b = np.ones((5, 2, 3))
c = np.transpose(b, (1, 2, 0))

# Multiply a and c
e = a * c

# Check if a and e are equal
print("Are a and e equal?", np.array_equal(a, e))  # This will return True




Are a and e equal? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [19]:
### [your code here]
import numpy as np

# Assuming d has already been defined from previous steps
# Example: d = a + c (where a and c are arrays you worked with before)

# Calculate max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Print the results
print(f"Max value in d: {d_max}")
print(f"Min value in d: {d_min}")
print(f"Mean value in d: {d_mean}")



Max value in d: 1.9671362043497493
Min value in d: 1.0518145047556822
Mean value in d: 1.5317720270520463



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [20]:
### [your code here]
import numpy as np

# Assuming d has already been defined with shape (2, 3, 5)
# Create an empty array "f" with the same shape as "d"
f = np.empty_like(d, dtype=object)  # Use dtype=object since we'll store labels (strings)

# Print f to see the initial empty array
print(f)



[[[None None None None None]
  [None None None None None]
  [None None None None None]]

 [[None None None None None]
  [None None None None None]
  [None None None None None]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [22]:
import numpy as np

# Example arrays a, d_min, d_max, and d_mean
a = np.random.rand(2, 3, 5)
d = np.random.rand(2, 3, 5) * 2  # Random values for d as an example
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

# Create an empty array "f" with the same shape as "d"
f = np.empty_like(d, dtype=object)  # Using dtype=object to store labels as strings

# Loop through each element in d and apply the conditions
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the resulting f
print("Array f:")
print(f)

          



Array f:
[[[25 25 75 25 25]
  [75 25 25 75 25]
  [75 25 75 75 75]]

 [[25 25 75 75 75]
  [75 75 75 25 25]
  [75 100 25 75 0]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [23]:
### [your code here]
import numpy as np

# Example d array
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Find min, max, and mean
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d
f = np.empty_like(d, dtype=float)  # Using float for numeric values

# Populate the values in f based on the conditions in one loop
f[(d == d_min)] = 0
f[(d == d_mean)] = 50
f[(d == d_max)] = 100
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75

# Print d and f
print("Array d:")
print(d)

print("\nArray f:")
print(f)





Array d:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

Array f:
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [24]:
### [your code here]
# Example d array
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Find min, max, and mean
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d but with string values
f = np.empty_like(d, dtype=object)  # Using object for string values

# Populate the values in f based on the conditions using strings
f[(d == d_min)] = "A"
f[(d == d_mean)] = "C"
f[(d == d_max)] = "E"
f[(d > d_min) & (d < d_mean)] = "B"
